
server:
  port: 8088

spring:
  application:
    name: pharma-pro-backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/roman
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update # Use update for development, none for production
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

# JWT configuration
jwt:
  secret: ${JWT_SECRET:change_this_to_a_strong_secret_key}
  expirationMs: 3600000   # 1 hour in milliseconds